apiVersion: apps/v1
kind: Deployment
metadata:
  name: endhunger
  labels:
    app: endhunger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: endhunger
  template:
    metadata:
      labels:
        app: endhunger
    spec:
      containers:
        - name: endhunger
          image: devenops641/endhunger:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
